### ISSUE TITLE
Invalid Mapper[ProductModel(products)]

### ISSUE THREAD

**Issue by gustavovalle23** [churros-py/churros-builder#7]
Steps to reproduce:
```bash
python mock_server.py
```

```bash
curl --request GET \
  --url http://localhost:8000/users/ \
  --header 'User-Agent: insomnia/9.2.0'
```

```bash
uvicorn src.main:app --reload
```

Stacktrace:

```bash
INFO:     127.0.0.1:61850 - "GET /users HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\fastapi\applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\fastapi\routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\fastapi\routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\src\infra\api\routers\user.py", line 16, in find_users
    users: Tuple[User] = user_repository.find_all(db, skip, limit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\src\infra\repositories\user.py", line 23, in find_all
    db.query(UserModel).offset(skip).limit(limit)
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2941, in query
    return self._query_cls(entities, self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 275, in __init__
    self._set_entities(entities)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 288, in _set_entities
    coercions.expect(
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\sql\coercions.py", line 389, in expect
    insp._post_inspect
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2711, in _post_inspect
    self._check_configure()
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2388, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4204, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "C:\Users\Gustavo\Documents\Github\churros-builder\venv\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4241, in _do_configure_registries
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[ProductModel(products)]'. Original exception was: When initializing mapper Mapper[ProductModel(products)], expression 'User' failed to locate a name ('User'). If this is a class name, consider adding this relationship() to the <class 'src.infra.schemas.product.ProductModel'> class after both dependent classes have been defined
```

**Comment by gustavovalle23** [comment]
Part of the issue is solved with this:
https://github.com/churros-py/churros-builder/pull/8

However I still need to find a way to set the "back_populates" relationship in the target model.
In our mock_server case, it would be in the UserModel

**Comment by gustavovalle23** [comment]
Permanent fix: https://github.com/churros-py/churros-builder/pull/17
